# Generated by Django 6.0.8 on 2026-09-10 21:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("iron_fe", "Iron (Fe)"),
                            ("copper_cu", "Copper (Cu)"),
                            ("aluminum_al", "Aluminum (Al)"),
                            ("chromium_cr", "Chromium (Cr)"),
                            ("lead_pb", "Lead (Pb)"),
                            ("tin_sn", "Tin (Sn)"),
                            ("nickel_ni", "Nickel (Ni)"),
                            ("silver_ag", "Silver (Ag)"),
                            ("silicon_si", "Silicon (Si)"),
                            ("sodium_na", "Sodium (Na)"),
                            ("potassium_k", "Potassium (K)"),
                            ("boron_b", "Boron (B)"),
                            ("viscosity_40c", "Viscosity @ 40C"),
                            ("viscosity_100c", "Viscosity @ 100C"),
                            ("tbn", "TBN (Total Base Number)"),
                            ("tan", "TAN (Total Acid Number)"),
                            ("oxidation", "Oxidation"),
                            ("nitration", "Nitration"),
                            ("sulfation", "Sulfation"),
                            ("glycol", "Glycol"),
                            ("fuel_dilution", "Fuel Dilution"),
                            ("pq_index", "PQ Index"),
                            ("zinc_zn", "Zinc (Zn)"),
                            ("phosphorus_p", "Phosphorus (P)"),
                            ("magnesium_mg", "Magnesium (Mg)"),
                            ("calcium_ca", "Calcium (Ca)"),
                            ("molybdenum_mo", "Molybdenum (Mo)"),
                            ("barium_ba", "Barium (Ba)"),
                            ("cadmium_cd", "Cadmium (Cd)"),
                            ("titanium_ti", "Titanium (Ti)"),
                            ("vanadium_v", "Vanadium (V)"),
                            ("manganese_mn", "Manganese (Mn)"),
                        ],
                        max_length=100,
                        verbose_name="Parameter",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wear_metals", "Wear Metals"),
                            ("contamination", "Contamination"),
                            ("oil_health", "Oil Health"),
                            ("additives", "Additives"),
                            ("particle_analysis", "Particle Analysis"),
                            ("ftir", "FTIR Analysis"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("CAUTION", "Caution"),
                            ("WARNING", "Warning"),
                        ],
                        default="CAUTION",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "warning_limit",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Warning Limit"
                    ),
                ),
                (
                    "critical_limit",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Critical Limit"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="ppm", max_length=20, verbose_name="Unit"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("THRESHOLD", "Threshold"),
                            ("TREND_RISING", "Trend Rising"),
                            ("TREND_DROP", "Trend Drop"),
                            ("PARAMETER_MISSING", "Parameter Missing"),
                        ],
                        default="THRESHOLD",
                        max_length=30,
                        verbose_name="Rule Type",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Detected At"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged At"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "sent_channels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Sent Channels"
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        help_text="Idempotency key",
                        max_length=200,
                        unique=True,
                        verbose_name="Dedup Key",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acknowledged By",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        help_text="Component associated with this alert",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="equipment.component",
                        verbose_name="Component",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Machine associated with this alert",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="equipment.machine",
                        verbose_name="Machine",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source report of this alert",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="reports.report",
                        verbose_name="Report",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ("-detected_at", "-created"),
                "permissions": [("acknowledge_alert", "Can acknowledge alert")],
                "indexes": [
                    models.Index(
                        fields=["status", "severity", "detected_at"],
                        name="alerts_aler_status_b7536d_idx",
                    ),
                    models.Index(
                        fields=["machine", "parameter", "detected_at"],
                        name="alerts_aler_machine_fc162d_idx",
                    ),
                ],
            },
        ),
    ]
