from typing import ClassVar

from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel

from apps.core import models as core_models
from apps.equipment import models as equipment_models
from apps.reports import choices


class Laboratory(
    TimeStampedModel,
    core_models.NameDescription,
    core_models.BaseUserTracked,
    core_models.IsActive,
):
    """
    Laboratory model.

    Represents a laboratory that performs oil analysis
    and generates inspection reports.
    """

    code = models.CharField(
        _("Code"),
        max_length=50,
        unique=True,
        help_text=_("Unique laboratory identification code"),
    )

    class Meta:
        verbose_name = _("Laboratory")
        verbose_name_plural = _("Laboratories")
        ordering = ("name",)
        indexes: ClassVar[list[models.Index]] = [
            models.Index(fields=["code"]),
            models.Index(fields=["is_active"]),
        ]

    def __str__(self) -> str:
        """Return string representation of the laboratory."""
        return f"{self.name} ({self.code})"


class Report(TimeStampedModel, core_models.BaseUserTracked, core_models.IsActive):
    """
    Report model.

    Represents inspection reports generated by external providers
    for equipment condition monitoring and predictive maintenance.
    """

    laboratory = models.ForeignKey(
        Laboratory,
        verbose_name=_("Laboratory"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        help_text=_("Laboratory that performed the analysis"),
    )
    machine = models.ForeignKey(
        equipment_models.Machine,
        verbose_name=_("Machine"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        help_text=_("Machine/Equipment associated with this report"),
    )
    component = models.ForeignKey(
        equipment_models.Component,
        verbose_name=_("Component"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        help_text=_("Component associated with this report"),
    )
    lab_number = models.CharField(
        _("Lab Number"),
        max_length=50,
        unique=True,
        help_text=_("Laboratory identification number (No. Lab)"),
    )
    lubricant = models.CharField(
        _("Lubricant"),
        max_length=200,
        blank=True,
        help_text=_("Lubricant type/brand used"),
    )
    lubricant_hours = models.IntegerField(
        _("Lubricant Hours"),
        null=True,
        blank=True,
        help_text=_("Hours of lubricant usage"),
    )
    lubricant_kms = models.IntegerField(
        _("Lubricant Kilometers"),
        null=True,
        blank=True,
        help_text=_("Kilometers of lubricant usage"),
    )
    machine_hours = models.IntegerField(
        _("Machine Hours"),
        null=True,
        blank=True,
        help_text=_("Total operating hours of the machine"),
    )
    machine_kms = models.IntegerField(
        _("Machine Kilometers"),
        null=True,
        blank=True,
        help_text=_("Total kilometers traveled by the machine"),
    )
    serial_number_code = models.CharField(
        _("Serial Number Code"),
        max_length=100,
        blank=True,
        help_text=_("Serial number code from the report (Cod./Num. De Serie)"),
    )
    sample_date = models.DateField(
        _("Sample Date"),
        null=True,
        blank=True,
        help_text=_("Date when the sample was taken (Fecha Muestra)"),
    )
    per_number = models.CharField(
        _("PER Number"),
        max_length=50,
        blank=True,
        help_text=_("PER identification number (No. PER)"),
    )
    reception_date = models.DateField(
        _("Reception Date"),
        null=True,
        blank=True,
        help_text=_("Date when the sample was received (Fecha de Recepción)"),
    )
    status = models.CharField(
        _("Status"),
        max_length=20,
        choices=choices.ReportStatus.choices,
        default=choices.ReportStatus.PENDING,
        help_text=_("Current status of the report"),
    )
    condition = models.CharField(
        _("Condition"),
        max_length=20,
        choices=choices.ReportCondition.choices,
        default=choices.ReportCondition.NORMAL,
        help_text=_("Equipment condition assessment"),
    )
    notes = models.TextField(
        _("Notes"),
        blank=True,
        help_text=_("Additional notes or observations"),
    )
    report_date = models.DateField(
        _("Report Date"),
        null=True,
        blank=True,
        help_text=_("Date when the report was generated (Fecha de Reporte)"),
    )
    filter_change = models.CharField(
        _("Filter Change"),
        max_length=20,
        blank=True,
        help_text=_("Filter change indicator (Cambio de Filtro)"),
    )
    oil_change = models.CharField(
        _("Oil Change"),
        max_length=20,
        blank=True,
        help_text=_("Oil change indicator (Cambio de Aceite)"),
    )
    others = models.TextField(
        _("Others"),
        blank=True,
        help_text=_("Other observations or notes (Otros)"),
    )
    recommendations = models.TextField(
        _("Recommendations"),
        blank=True,
        help_text=_("Laboratory-specific recommendations (Recomendaciones)"),
    )
    component_hour_meter = models.IntegerField(
        _("Component Hour Meter"),
        null=True,
        blank=True,
        help_text=_(
            "Hours on component since installation (Horometro Instalacion Componente)"
        ),
    )
    previous_hour_meter = models.IntegerField(
        _("Previous Hour Meter"),
        null=True,
        blank=True,
        help_text=_("Machine hour meter from the previous sample (Horometro previo)"),
    )
    sampling_type = models.CharField(
        _("Sampling Type"),
        max_length=20,
        blank=True,
        help_text=_("Type of sample collection (INSP/PORT)"),
    )
    pm_position = models.CharField(
        _("PM Position"),
        max_length=20,
        blank=True,
        help_text=_(
            "Position relative to preventive maintenance (PRE-PM/POST-PM/INSP)"
        ),
    )
    action_required = models.TextField(
        _("Action Required"),
        blank=True,
        help_text=_("Specific action recommended by the laboratory (Accion a tomar)"),
    )
    turnaround_days = models.IntegerField(
        _("Turnaround Days"),
        null=True,
        blank=True,
        help_text=_("Laboratory turnaround time in days (TR dias)"),
    )

    class Meta:
        verbose_name = _("Report")
        verbose_name_plural = _("Reports")
        ordering = ("-sample_date", "-created")
        indexes: ClassVar[list[models.Index]] = [
            models.Index(fields=["lab_number"]),
            models.Index(fields=["per_number"]),
            models.Index(fields=["sample_date"]),
            models.Index(fields=["is_active"]),
            models.Index(fields=["machine", "is_active"]),
            models.Index(fields=["status"]),
            models.Index(fields=["condition"]),
        ]

    def __str__(self) -> str:
        """Return string representation of report."""
        return f"Report {self.lab_number} - {self.get_condition_display()}"

    @cached_property
    def component_name(self) -> str:
        """Return the name of the associated component, or 'N/A' if none."""
        return self.component.type.name if self.component else "N/A"


class LabAnalysis(TimeStampedModel, core_models.BaseUserTracked):
    """
    Laboratory Analysis Results.

    Stores all physicochemical measurements, wear metals,
    contaminants, and additives from oil analysis.
    One-to-one relationship with Report.
    """

    report = models.OneToOneField(
        Report,
        verbose_name=_("Report"),
        on_delete=models.CASCADE,
        related_name="analysis",
        help_text=_("Associated inspection report"),
    )

    # ==========================================
    # WATER TESTS
    # ==========================================
    water_crackle = models.CharField(
        _("Water Crackle Test"),
        max_length=50,
        blank=True,
        help_text=_("ITS 009/18 - Qualitative water test (NEGATIVO/POSITIVO)"),
    )
    water_distillation = models.DecimalField(
        _("Water by Distillation (%)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
        help_text=_("ASTM D 95-13"),
    )

    # ==========================================
    # VISCOSITY
    # ==========================================
    viscosity_40c = models.DecimalField(
        _("Viscosity @ 40°C (cSt)"),
        max_digits=8,
        decimal_places=3,
        null=True,
        blank=True,
        help_text=_("ASTM D 7279-20"),
    )
    viscosity_100c = models.DecimalField(
        _("Viscosity @ 100°C (cSt)"),
        max_digits=8,
        decimal_places=3,
        null=True,
        blank=True,
        help_text=_("ASTM D 7279-20"),
    )

    # ==========================================
    # VISCOSITY (continued)
    # ==========================================
    viscosity_index = models.IntegerField(
        _("Viscosity Index (VI)"),
        null=True,
        blank=True,
        help_text=_("Calculated viscosity index; indicates VI-improver degradation"),
    )

    # ==========================================
    # WATER TESTS (continued)
    # ==========================================
    refrigerant_pct = models.DecimalField(
        _("Refrigerant (%)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
        help_text=_("Refrigerant contamination percentage (distinct from glycol FTIR)"),
    )

    # ==========================================
    # ACID/BASE NUMBERS
    # ==========================================
    compatibility = models.CharField(
        _("Compatibility"),
        max_length=50,
        blank=True,
        help_text=_("ILT-096 - Compatibility test result"),
    )
    tbn = models.DecimalField(
        _("TBN (mgKOH/g)"),
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_("ASTM D 2896-21 - Total Base Number"),
    )
    tan = models.DecimalField(
        _("TAN (mgKOH/g)"),
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_("ASTM D 664-24 - Total Acid Number"),
    )

    # ==========================================
    # FTIR ANALYSIS (ASTM E 2412-23)
    # ==========================================
    oxidation = models.DecimalField(
        _("Oxidation (Abs/cm)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
    )
    soot = models.DecimalField(
        _("Soot (%)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
    )
    nitration = models.DecimalField(
        _("Nitration (Abs/cm)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
    )
    sulfation = models.DecimalField(
        _("Sulfation (Abs/cm)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
    )
    glycol = models.DecimalField(
        _("Glycol (%)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
    )
    fuel_dilution = models.DecimalField(
        _("Fuel Dilution (%)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
    )
    water_ftir = models.DecimalField(
        _("Water FTIR (%)"),
        max_digits=6,
        decimal_places=3,
        null=True,
        blank=True,
    )

    # ==========================================
    # PARTICLE ANALYSIS
    # ==========================================
    pq_index = models.IntegerField(
        _("PQ Index"),
        null=True,
        blank=True,
        help_text=_("ITS 044/15 - Ferrous particle index"),
    )
    particle_count_iso = models.CharField(
        _("Particle Count ISO"),
        max_length=50,
        blank=True,
        help_text=_("ISO 4406:2021 (e.g., 20/18/15)"),
    )
    # ISO 4406 granulometric distribution (particles/mL per size range)
    particle_4um = models.IntegerField(
        _("Particles < 4 µm (c/mL)"),
        null=True,
        blank=True,
        help_text=_("ISO 4406 - Particle count for size < 4 µm"),
    )
    particle_6um = models.IntegerField(
        _("Particles < 6 µm (c/mL)"),
        null=True,
        blank=True,
        help_text=_("ISO 4406 - Particle count for size < 6 µm"),
    )
    particle_14um = models.IntegerField(
        _("Particles < 14 µm (c/mL)"),
        null=True,
        blank=True,
        help_text=_("ISO 4406 - Particle count for size < 14 µm"),
    )
    particle_21um = models.IntegerField(
        _("Particles < 21 µm (c/mL)"),
        null=True,
        blank=True,
        help_text=_("ISO 4406 - Particle count for size < 21 µm"),
    )
    particle_38um = models.IntegerField(
        _("Particles < 38 µm (c/mL)"),
        null=True,
        blank=True,
        help_text=_("ISO 4406 - Particle count for size < 38 µm"),
    )
    particle_70um = models.IntegerField(
        _("Particles < 70 µm (c/mL)"),
        null=True,
        blank=True,
        help_text=_("ISO 4406 - Particle count for size < 70 µm"),
    )

    # ==========================================
    # WEAR METALS (ppm) - ASTM D 5185-18
    # ==========================================
    iron_fe = models.IntegerField(_("Iron (Fe)"), null=True, blank=True)
    chromium_cr = models.IntegerField(_("Chromium (Cr)"), null=True, blank=True)
    lead_pb = models.IntegerField(_("Lead (Pb)"), null=True, blank=True)
    copper_cu = models.IntegerField(_("Copper (Cu)"), null=True, blank=True)
    tin_sn = models.IntegerField(_("Tin (Sn)"), null=True, blank=True)
    aluminum_al = models.IntegerField(_("Aluminum (Al)"), null=True, blank=True)
    nickel_ni = models.IntegerField(_("Nickel (Ni)"), null=True, blank=True)
    silver_ag = models.IntegerField(_("Silver (Ag)"), null=True, blank=True)

    # ==========================================
    # CONTAMINANTS (ppm)
    # ==========================================
    silicon_si = models.IntegerField(_("Silicon (Si)"), null=True, blank=True)
    boron_b = models.IntegerField(_("Boron (B)"), null=True, blank=True)
    sodium_na = models.IntegerField(_("Sodium (Na)"), null=True, blank=True)
    magnesium_mg = models.IntegerField(_("Magnesium (Mg)"), null=True, blank=True)
    potassium_k = models.IntegerField(_("Potassium (K)"), null=True, blank=True)

    # Qualitative contamination tests
    dispersancy = models.CharField(
        _("Dispersancy"),
        max_length=20,
        blank=True,
        help_text=_("Oil dispersancy rating (BUE/REG/MALA)"),
    )
    spot_test = models.CharField(
        _("Spot Test"),
        max_length=100,
        blank=True,
        help_text=_("Qualitative spot test for contamination"),
    )

    # ==========================================
    # ADDITIVES (ppm)
    # ==========================================
    molybdenum_mo = models.IntegerField(_("Molybdenum (Mo)"), null=True, blank=True)
    titanium_ti = models.IntegerField(_("Titanium (Ti)"), null=True, blank=True)
    vanadium_v = models.IntegerField(_("Vanadium (V)"), null=True, blank=True)
    manganese_mn = models.IntegerField(_("Manganese (Mn)"), null=True, blank=True)
    phosphorus_p = models.IntegerField(_("Phosphorus (P)"), null=True, blank=True)
    zinc_zn = models.IntegerField(_("Zinc (Zn)"), null=True, blank=True)
    calcium_ca = models.IntegerField(_("Calcium (Ca)"), null=True, blank=True)
    barium_ba = models.IntegerField(_("Barium (Ba)"), null=True, blank=True)
    cadmium_cd = models.IntegerField(_("Cadmium (Cd)"), null=True, blank=True)

    # ==========================================
    # VISUAL
    # ==========================================
    visual_appearance = models.CharField(
        _("Visual Appearance"),
        max_length=200,
        blank=True,
    )

    class Meta:
        verbose_name = _("Lab Analysis")
        verbose_name_plural = _("Lab Analyses")

    def __str__(self) -> str:
        return f"Analysis: {self.report.lab_number}"

    # ==========================================
    # COMPUTED PROPERTIES FOR DASHBOARDS
    # ==========================================
    @property
    def total_wear_metals(self) -> int:
        """Sum of primary wear metals (Fe, Cr, Pb, Cu, Sn, Al)."""
        metals = [
            self.iron_fe,
            self.chromium_cr,
            self.lead_pb,
            self.copper_cu,
            self.tin_sn,
            self.aluminum_al,
        ]
        return sum(m or 0 for m in metals)

    @property
    def total_contaminants(self) -> int:
        """Sum of contaminant elements (Si, Na, K)."""
        contaminants = [self.silicon_si, self.sodium_na, self.potassium_k]
        return sum(c or 0 for c in contaminants)

    @property
    def additive_depletion_pct(self) -> float | None:
        """Estimate additive health based on Zn levels."""
        if self.zinc_zn:
            return min(100.0, (self.zinc_zn / 1100) * 100)
        return None


class AnalysisThreshold(
    TimeStampedModel, core_models.BaseUserTracked, core_models.IsActive
):
    """
    Model to manage thresholds/limits for component analysis parameters.

    Thresholds can be specific to a component type or global (when component_type is null).
    When loading thresholds, component type-specific ones take priority over globals.
    Allows dynamic configuration of warning and critical limits
    for various analysis parameters through Django admin.
    """

    component_type = models.ForeignKey(
        equipment_models.ComponentType,
        verbose_name=_("Component Type"),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="analysis_thresholds",
        help_text=_("If null, applies as global default for all component types"),
    )
    category = models.CharField(
        _("Category"),
        max_length=50,
        choices=choices.Category.choices,
        help_text=_("Category this threshold belongs to"),
    )
    parameter = models.CharField(
        _("Parameter"),
        max_length=100,
        choices=choices.Parameter.choices,
        help_text=_("Parameter for this threshold"),
    )
    warning_limit = models.FloatField(
        _("Warning Limit"),
        help_text=_("Warning threshold value"),
    )
    critical_limit = models.FloatField(
        _("Critical Limit"),
        help_text=_("Critical threshold value"),
    )
    unit = models.CharField(
        _("Unit"),
        max_length=20,
        default="ppm",
        help_text=_("Measurement unit (ppm, cSt, etc.)"),
    )
    is_inverse = models.BooleanField(
        _("Is Inverse Logic"),
        default=False,
        help_text=_(
            "If True, values below limits are problematic (e.g., additives). "
            "If False, values above limits are problematic (e.g., wear metals)."
        ),
    )
    wear_source_description = models.TextField(
        _("Wear Source Description"),
        blank=True,
        help_text=_("Description of the wear source for this parameter"),
    )

    class Meta:
        verbose_name = _("Analysis Threshold")
        verbose_name_plural = _("Analysis Thresholds")
        ordering = ("component_type", "category", "parameter")
        unique_together = (("component_type", "category", "parameter"),)
        indexes: ClassVar[list[models.Index]] = [
            models.Index(fields=["component_type", "category", "parameter"]),
            models.Index(fields=["is_active"]),
        ]

    def __str__(self) -> str:
        """Return string representation of the threshold."""
        component_name = (
            self.component_type.name if self.component_type else _("Global")
        )
        return f"{component_name} - {self.get_category_display()} - {self.get_parameter_display()}"
