# Generated by Django 6.0.8 on 2026-09-10 20:33

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this entry is active",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique laboratory identification code",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratory",
                "verbose_name_plural": "Laboratories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this entry is active",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "lab_number",
                    models.CharField(
                        help_text="Laboratory identification number (No. Lab)",
                        max_length=50,
                        unique=True,
                        verbose_name="Lab Number",
                    ),
                ),
                (
                    "lubricant",
                    models.CharField(
                        blank=True,
                        help_text="Lubricant type/brand used",
                        max_length=200,
                        verbose_name="Lubricant",
                    ),
                ),
                (
                    "lubricant_hours",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours of lubricant usage",
                        null=True,
                        verbose_name="Lubricant Hours",
                    ),
                ),
                (
                    "lubricant_kms",
                    models.IntegerField(
                        blank=True,
                        help_text="Kilometers of lubricant usage",
                        null=True,
                        verbose_name="Lubricant Kilometers",
                    ),
                ),
                (
                    "machine_hours",
                    models.IntegerField(
                        blank=True,
                        help_text="Total operating hours of the machine",
                        null=True,
                        verbose_name="Machine Hours",
                    ),
                ),
                (
                    "machine_kms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total kilometers traveled by the machine",
                        null=True,
                        verbose_name="Machine Kilometers",
                    ),
                ),
                (
                    "serial_number_code",
                    models.CharField(
                        blank=True,
                        help_text="Serial number code from the report (Cod./Num. De Serie)",
                        max_length=100,
                        verbose_name="Serial Number Code",
                    ),
                ),
                (
                    "sample_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the sample was taken (Fecha Muestra)",
                        null=True,
                        verbose_name="Sample Date",
                    ),
                ),
                (
                    "per_number",
                    models.CharField(
                        blank=True,
                        help_text="PER identification number (No. PER)",
                        max_length=50,
                        verbose_name="PER Number",
                    ),
                ),
                (
                    "reception_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the sample was received (Fecha de Recepción)",
                        null=True,
                        verbose_name="Reception Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Current status of the report",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        help_text="Equipment condition assessment",
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or observations",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the report was generated (Fecha de Reporte)",
                        null=True,
                        verbose_name="Report Date",
                    ),
                ),
                (
                    "filter_change",
                    models.CharField(
                        blank=True,
                        help_text="Filter change indicator (Cambio de Filtro)",
                        max_length=20,
                        verbose_name="Filter Change",
                    ),
                ),
                (
                    "oil_change",
                    models.CharField(
                        blank=True,
                        help_text="Oil change indicator (Cambio de Aceite)",
                        max_length=20,
                        verbose_name="Oil Change",
                    ),
                ),
                (
                    "others",
                    models.TextField(
                        blank=True,
                        help_text="Other observations or notes (Otros)",
                        verbose_name="Others",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Laboratory-specific recommendations (Recomendaciones)",
                        verbose_name="Recommendations",
                    ),
                ),
                (
                    "component_hour_meter",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours on component since installation (Horometro Instalacion Componente)",
                        null=True,
                        verbose_name="Component Hour Meter",
                    ),
                ),
                (
                    "previous_hour_meter",
                    models.IntegerField(
                        blank=True,
                        help_text="Machine hour meter from the previous sample (Horometro previo)",
                        null=True,
                        verbose_name="Previous Hour Meter",
                    ),
                ),
                (
                    "sampling_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of sample collection (INSP/PORT)",
                        max_length=20,
                        verbose_name="Sampling Type",
                    ),
                ),
                (
                    "pm_position",
                    models.CharField(
                        blank=True,
                        help_text="Position relative to preventive maintenance (PRE-PM/POST-PM/INSP)",
                        max_length=20,
                        verbose_name="PM Position",
                    ),
                ),
                (
                    "action_required",
                    models.TextField(
                        blank=True,
                        help_text="Specific action recommended by the laboratory (Accion a tomar)",
                        verbose_name="Action Required",
                    ),
                ),
                (
                    "turnaround_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Laboratory turnaround time in days (TR dias)",
                        null=True,
                        verbose_name="Turnaround Days",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        help_text="Component associated with this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="equipment.component",
                        verbose_name="Component",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laboratory that performed the analysis",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="reports.laboratory",
                        verbose_name="Laboratory",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Machine/Equipment associated with this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="equipment.machine",
                        verbose_name="Machine",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ("-sample_date", "-created"),
            },
        ),
        migrations.CreateModel(
            name="LabAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "water_crackle",
                    models.CharField(
                        blank=True,
                        help_text="ITS 009/18 - Qualitative water test (NEGATIVO/POSITIVO)",
                        max_length=50,
                        verbose_name="Water Crackle Test",
                    ),
                ),
                (
                    "water_distillation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ASTM D 95-13",
                        max_digits=6,
                        null=True,
                        verbose_name="Water by Distillation (%)",
                    ),
                ),
                (
                    "viscosity_40c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ASTM D 7279-20",
                        max_digits=8,
                        null=True,
                        verbose_name="Viscosity @ 40°C (cSt)",
                    ),
                ),
                (
                    "viscosity_100c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ASTM D 7279-20",
                        max_digits=8,
                        null=True,
                        verbose_name="Viscosity @ 100°C (cSt)",
                    ),
                ),
                (
                    "viscosity_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Calculated viscosity index; indicates VI-improver degradation",
                        null=True,
                        verbose_name="Viscosity Index (VI)",
                    ),
                ),
                (
                    "refrigerant_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Refrigerant contamination percentage (distinct from glycol FTIR)",
                        max_digits=6,
                        null=True,
                        verbose_name="Refrigerant (%)",
                    ),
                ),
                (
                    "compatibility",
                    models.CharField(
                        blank=True,
                        help_text="ILT-096 - Compatibility test result",
                        max_length=50,
                        verbose_name="Compatibility",
                    ),
                ),
                (
                    "tbn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ASTM D 2896-21 - Total Base Number",
                        max_digits=6,
                        null=True,
                        verbose_name="TBN (mgKOH/g)",
                    ),
                ),
                (
                    "tan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ASTM D 664-24 - Total Acid Number",
                        max_digits=6,
                        null=True,
                        verbose_name="TAN (mgKOH/g)",
                    ),
                ),
                (
                    "oxidation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Oxidation (Abs/cm)",
                    ),
                ),
                (
                    "soot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Soot (%)",
                    ),
                ),
                (
                    "nitration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Nitration (Abs/cm)",
                    ),
                ),
                (
                    "sulfation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Sulfation (Abs/cm)",
                    ),
                ),
                (
                    "glycol",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Glycol (%)",
                    ),
                ),
                (
                    "fuel_dilution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Fuel Dilution (%)",
                    ),
                ),
                (
                    "water_ftir",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Water FTIR (%)",
                    ),
                ),
                (
                    "pq_index",
                    models.IntegerField(
                        blank=True,
                        help_text="ITS 044/15 - Ferrous particle index",
                        null=True,
                        verbose_name="PQ Index",
                    ),
                ),
                (
                    "particle_count_iso",
                    models.CharField(
                        blank=True,
                        help_text="ISO 4406:2021 (e.g., 20/18/15)",
                        max_length=50,
                        verbose_name="Particle Count ISO",
                    ),
                ),
                (
                    "particle_4um",
                    models.IntegerField(
                        blank=True,
                        help_text="ISO 4406 - Particle count for size < 4 µm",
                        null=True,
                        verbose_name="Particles < 4 µm (c/mL)",
                    ),
                ),
                (
                    "particle_6um",
                    models.IntegerField(
                        blank=True,
                        help_text="ISO 4406 - Particle count for size < 6 µm",
                        null=True,
                        verbose_name="Particles < 6 µm (c/mL)",
                    ),
                ),
                (
                    "particle_14um",
                    models.IntegerField(
                        blank=True,
                        help_text="ISO 4406 - Particle count for size < 14 µm",
                        null=True,
                        verbose_name="Particles < 14 µm (c/mL)",
                    ),
                ),
                (
                    "particle_21um",
                    models.IntegerField(
                        blank=True,
                        help_text="ISO 4406 - Particle count for size < 21 µm",
                        null=True,
                        verbose_name="Particles < 21 µm (c/mL)",
                    ),
                ),
                (
                    "particle_38um",
                    models.IntegerField(
                        blank=True,
                        help_text="ISO 4406 - Particle count for size < 38 µm",
                        null=True,
                        verbose_name="Particles < 38 µm (c/mL)",
                    ),
                ),
                (
                    "particle_70um",
                    models.IntegerField(
                        blank=True,
                        help_text="ISO 4406 - Particle count for size < 70 µm",
                        null=True,
                        verbose_name="Particles < 70 µm (c/mL)",
                    ),
                ),
                (
                    "iron_fe",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Iron (Fe)"
                    ),
                ),
                (
                    "chromium_cr",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Chromium (Cr)"
                    ),
                ),
                (
                    "lead_pb",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Lead (Pb)"
                    ),
                ),
                (
                    "copper_cu",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Copper (Cu)"
                    ),
                ),
                (
                    "tin_sn",
                    models.IntegerField(blank=True, null=True, verbose_name="Tin (Sn)"),
                ),
                (
                    "aluminum_al",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Aluminum (Al)"
                    ),
                ),
                (
                    "nickel_ni",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nickel (Ni)"
                    ),
                ),
                (
                    "silver_ag",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Silver (Ag)"
                    ),
                ),
                (
                    "silicon_si",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Silicon (Si)"
                    ),
                ),
                (
                    "boron_b",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Boron (B)"
                    ),
                ),
                (
                    "sodium_na",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sodium (Na)"
                    ),
                ),
                (
                    "magnesium_mg",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Magnesium (Mg)"
                    ),
                ),
                (
                    "potassium_k",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Potassium (K)"
                    ),
                ),
                (
                    "dispersancy",
                    models.CharField(
                        blank=True,
                        help_text="Oil dispersancy rating (BUE/REG/MALA)",
                        max_length=20,
                        verbose_name="Dispersancy",
                    ),
                ),
                (
                    "spot_test",
                    models.CharField(
                        blank=True,
                        help_text="Qualitative spot test for contamination",
                        max_length=100,
                        verbose_name="Spot Test",
                    ),
                ),
                (
                    "molybdenum_mo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Molybdenum (Mo)"
                    ),
                ),
                (
                    "titanium_ti",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Titanium (Ti)"
                    ),
                ),
                (
                    "vanadium_v",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Vanadium (V)"
                    ),
                ),
                (
                    "manganese_mn",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Manganese (Mn)"
                    ),
                ),
                (
                    "phosphorus_p",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Phosphorus (P)"
                    ),
                ),
                (
                    "zinc_zn",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Zinc (Zn)"
                    ),
                ),
                (
                    "calcium_ca",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Calcium (Ca)"
                    ),
                ),
                (
                    "barium_ba",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Barium (Ba)"
                    ),
                ),
                (
                    "cadmium_cd",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Cadmium (Cd)"
                    ),
                ),
                (
                    "visual_appearance",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Visual Appearance"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        help_text="Associated inspection report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="reports.report",
                        verbose_name="Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Analysis",
                "verbose_name_plural": "Lab Analyses",
            },
        ),
        migrations.CreateModel(
            name="AnalysisThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this entry is active",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wear_metals", "Wear Metals"),
                            ("contamination", "Contamination"),
                            ("oil_health", "Oil Health"),
                            ("additives", "Additives"),
                            ("particle_analysis", "Particle Analysis"),
                            ("ftir", "FTIR Analysis"),
                        ],
                        help_text="Category this threshold belongs to",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("iron_fe", "Iron (Fe)"),
                            ("copper_cu", "Copper (Cu)"),
                            ("aluminum_al", "Aluminum (Al)"),
                            ("chromium_cr", "Chromium (Cr)"),
                            ("lead_pb", "Lead (Pb)"),
                            ("tin_sn", "Tin (Sn)"),
                            ("nickel_ni", "Nickel (Ni)"),
                            ("silver_ag", "Silver (Ag)"),
                            ("silicon_si", "Silicon (Si)"),
                            ("sodium_na", "Sodium (Na)"),
                            ("potassium_k", "Potassium (K)"),
                            ("boron_b", "Boron (B)"),
                            ("viscosity_40c", "Viscosity @ 40C"),
                            ("viscosity_100c", "Viscosity @ 100C"),
                            ("tbn", "TBN (Total Base Number)"),
                            ("tan", "TAN (Total Acid Number)"),
                            ("oxidation", "Oxidation"),
                            ("nitration", "Nitration"),
                            ("sulfation", "Sulfation"),
                            ("glycol", "Glycol"),
                            ("fuel_dilution", "Fuel Dilution"),
                            ("pq_index", "PQ Index"),
                            ("zinc_zn", "Zinc (Zn)"),
                            ("phosphorus_p", "Phosphorus (P)"),
                            ("magnesium_mg", "Magnesium (Mg)"),
                            ("calcium_ca", "Calcium (Ca)"),
                            ("molybdenum_mo", "Molybdenum (Mo)"),
                            ("barium_ba", "Barium (Ba)"),
                            ("cadmium_cd", "Cadmium (Cd)"),
                            ("titanium_ti", "Titanium (Ti)"),
                            ("vanadium_v", "Vanadium (V)"),
                            ("manganese_mn", "Manganese (Mn)"),
                        ],
                        help_text="Parameter for this threshold",
                        max_length=100,
                        verbose_name="Parameter",
                    ),
                ),
                (
                    "warning_limit",
                    models.FloatField(
                        help_text="Warning threshold value",
                        verbose_name="Warning Limit",
                    ),
                ),
                (
                    "critical_limit",
                    models.FloatField(
                        help_text="Critical threshold value",
                        verbose_name="Critical Limit",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="ppm",
                        help_text="Measurement unit (ppm, cSt, etc.)",
                        max_length=20,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "is_inverse",
                    models.BooleanField(
                        default=False,
                        help_text="If True, values below limits are problematic (e.g., additives). If False, values above limits are problematic (e.g., wear metals).",
                        verbose_name="Is Inverse Logic",
                    ),
                ),
                (
                    "wear_source_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the wear source for this parameter",
                        verbose_name="Wear Source Description",
                    ),
                ),
                (
                    "component_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies as global default for all component types",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_thresholds",
                        to="equipment.componenttype",
                        verbose_name="Component Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis Threshold",
                "verbose_name_plural": "Analysis Thresholds",
                "ordering": ("component_type", "category", "parameter"),
                "indexes": [
                    models.Index(
                        fields=["component_type", "category", "parameter"],
                        name="reports_ana_compone_80aeaf_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="reports_ana_is_acti_043f42_idx"
                    ),
                ],
                "unique_together": {("component_type", "category", "parameter")},
            },
        ),
        migrations.AddIndex(
            model_name="laboratory",
            index=models.Index(fields=["code"], name="reports_lab_code_49c213_idx"),
        ),
        migrations.AddIndex(
            model_name="laboratory",
            index=models.Index(
                fields=["is_active"], name="reports_lab_is_acti_431518_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["lab_number"], name="reports_rep_lab_num_d8e1d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["per_number"], name="reports_rep_per_num_c81495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["sample_date"], name="reports_rep_sample__f82eda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["is_active"], name="reports_rep_is_acti_d57b35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["machine", "is_active"], name="reports_rep_machine_86ea8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="reports_rep_status_c732ef_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["condition"], name="reports_rep_conditi_2e0a81_idx"
            ),
        ),
    ]
