# Generated by Django 6.0.8 on 2026-09-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-sample_date', '-created'), 'permissions': [('view_component_analysis', 'Can view component analysis')], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
